// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "test-softtek",
    "version": "1"
  },
  "paths": {
    "/": {
      "get": {
        "summary": "getPeople",
        "description": "",
        "operationId": "getPeople.get./",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/create": {
      "post": {
        "summary": "createUser",
        "description": "",
        "operationId": "createUser.post./create",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/users": {
      "get": {
        "summary": "getUsers",
        "description": "",
        "operationId": "getUsers.get./users",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};